
# Site settings
baseurl = "https://venkyyuvy.github.io/"
title = "Venkatachalam Natchiappan"
languageCode = "en-us"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "projects"
  url = "projects/"

  [[params.navlinks]]
  name = "blogs"
  url = "blogs/"

  [[params.navlinks]]
  name = "lifestyle"
  url = "lifestyle/"

  [[params.navlinks]]
  name = "photos"
  url = "photos/"

