
# Site settings
baseurl = "https://venkyyuvy.github.io/"
title = "Venkatachalam"
languageCode = "en-us"
theme = "hugo-theme-console"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false


  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "blog/"
  url = "blog/"

  [[params.navlinks]]
  name = "fitness/"
  url = "fitness/"

  [[params.navlinks]]
  name = "stories/"
  url = "stories/"


